#This Dockerfile builds Apache JMeter Master Executable
FROM vishnumurty/jmbase
MAINTAINER vishnumurty
LABEL Description="This image is used to start the Apache JMeter Master Executable"

#Port 60000 required for JMeter Master
EXPOSE 60000
